language: python
cache: pip
dist: bionic

python:
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
    - pypy3

env:
    - TOXENV=py

jobs:
    include:
        - python: '3.8'
          env: TOXENV=dogfood
        - python: '3.8'
          env: TOXENV=typing

install:
    - pip install codecov tox
script:
    - tox
after_success:
    - codecov
